// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.github.bean.protobuf;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.bean.protobuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    boolean hasStrObj();
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    java.lang.String getStrObj();
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    com.google.protobuf.ByteString
        getStrObjBytes();

    /**
     * <code>optional int32 int32Obj = 2;</code>
     */
    boolean hasInt32Obj();
    /**
     * <code>optional int32 int32Obj = 2;</code>
     */
    int getInt32Obj();

    /**
     * <code>optional int64 int64Obj = 3;</code>
     */
    boolean hasInt64Obj();
    /**
     * <code>optional int64 int64Obj = 3;</code>
     */
    long getInt64Obj();

    /**
     * <code>optional bool boolObj = 12;</code>
     */
    boolean hasBoolObj();
    /**
     * <code>optional bool boolObj = 12;</code>
     */
    boolean getBoolObj();

    /**
     * <code>optional bytes bytesObj = 13;</code>
     */
    boolean hasBytesObj();
    /**
     * <code>optional bytes bytesObj = 13;</code>
     */
    com.google.protobuf.ByteString getBytesObj();

    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated boolean hasFolatObj();
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated float getFolatObj();

    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    java.util.List<java.lang.Double> getDoubleObjList();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    int getDoubleObjCount();
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    double getDoubleObj(int index);

    /**
     * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
     */
    boolean hasInnerMessage();
    /**
     * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
     */
    com.github.bean.protobuf.InnerMessageProtos.InnerMessage getInnerMessage();
    /**
     * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
     */
    com.github.bean.protobuf.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder();
  }
  /**
   * Protobuf type {@code com.github.bean.protobuf.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.bean.protobuf.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      strObj_ = "hello";
      int32Obj_ = 0;
      int64Obj_ = 0L;
      boolObj_ = false;
      bytesObj_ = com.google.protobuf.ByteString.EMPTY;
      folatObj_ = 0F;
      doubleObj_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              strObj_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              int32Obj_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              int64Obj_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000008;
              boolObj_ = input.readBool();
              break;
            }
            case 106: {
              bitField0_ |= 0x00000010;
              bytesObj_ = input.readBytes();
              break;
            }
            case 117: {
              bitField0_ |= 0x00000020;
              folatObj_ = input.readFloat();
              break;
            }
            case 121: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                doubleObj_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000040;
              }
              doubleObj_.add(input.readDouble());
              break;
            }
            case 122: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                doubleObj_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                doubleObj_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 130: {
              com.github.bean.protobuf.InnerMessageProtos.InnerMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = innerMessage_.toBuilder();
              }
              innerMessage_ = input.readMessage(com.github.bean.protobuf.InnerMessageProtos.InnerMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(innerMessage_);
                innerMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          doubleObj_ = java.util.Collections.unmodifiableList(doubleObj_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.bean.protobuf.MessageProtos.internal_static_com_github_bean_protobuf_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.bean.protobuf.MessageProtos.internal_static_com_github_bean_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.bean.protobuf.MessageProtos.Message.class, com.github.bean.protobuf.MessageProtos.Message.Builder.class);
    }

    private int bitField0_;
    public static final int STROBJ_FIELD_NUMBER = 1;
    private volatile java.lang.Object strObj_;
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    public boolean hasStrObj() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    public java.lang.String getStrObj() {
      java.lang.Object ref = strObj_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strObj_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string strObj = 1 [default = "hello"];</code>
     */
    public com.google.protobuf.ByteString
        getStrObjBytes() {
      java.lang.Object ref = strObj_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strObj_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INT32OBJ_FIELD_NUMBER = 2;
    private int int32Obj_;
    /**
     * <code>optional int32 int32Obj = 2;</code>
     */
    public boolean hasInt32Obj() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 int32Obj = 2;</code>
     */
    public int getInt32Obj() {
      return int32Obj_;
    }

    public static final int INT64OBJ_FIELD_NUMBER = 3;
    private long int64Obj_;
    /**
     * <code>optional int64 int64Obj = 3;</code>
     */
    public boolean hasInt64Obj() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 int64Obj = 3;</code>
     */
    public long getInt64Obj() {
      return int64Obj_;
    }

    public static final int BOOLOBJ_FIELD_NUMBER = 12;
    private boolean boolObj_;
    /**
     * <code>optional bool boolObj = 12;</code>
     */
    public boolean hasBoolObj() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool boolObj = 12;</code>
     */
    public boolean getBoolObj() {
      return boolObj_;
    }

    public static final int BYTESOBJ_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString bytesObj_;
    /**
     * <code>optional bytes bytesObj = 13;</code>
     */
    public boolean hasBytesObj() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes bytesObj = 13;</code>
     */
    public com.google.protobuf.ByteString getBytesObj() {
      return bytesObj_;
    }

    public static final int FOLATOBJ_FIELD_NUMBER = 14;
    private float folatObj_;
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated public boolean hasFolatObj() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional float folatObj = 14 [deprecated = true];</code>
     */
    @java.lang.Deprecated public float getFolatObj() {
      return folatObj_;
    }

    public static final int DOUBLEOBJ_FIELD_NUMBER = 15;
    private java.util.List<java.lang.Double> doubleObj_;
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    public java.util.List<java.lang.Double>
        getDoubleObjList() {
      return doubleObj_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    public int getDoubleObjCount() {
      return doubleObj_.size();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>repeated double doubleObj = 15 [packed = true];</code>
     */
    public double getDoubleObj(int index) {
      return doubleObj_.get(index);
    }
    private int doubleObjMemoizedSerializedSize = -1;

    public static final int INNERMESSAGE_FIELD_NUMBER = 16;
    private com.github.bean.protobuf.InnerMessageProtos.InnerMessage innerMessage_;
    /**
     * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
     */
    public boolean hasInnerMessage() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
     */
    public com.github.bean.protobuf.InnerMessageProtos.InnerMessage getInnerMessage() {
      return innerMessage_ == null ? com.github.bean.protobuf.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
    }
    /**
     * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
     */
    public com.github.bean.protobuf.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder() {
      return innerMessage_ == null ? com.github.bean.protobuf.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStrObj()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, strObj_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, int32Obj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, int64Obj_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(12, boolObj_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(13, bytesObj_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(14, folatObj_);
      }
      if (getDoubleObjList().size() > 0) {
        output.writeUInt32NoTag(122);
        output.writeUInt32NoTag(doubleObjMemoizedSerializedSize);
      }
      for (int i = 0; i < doubleObj_.size(); i++) {
        output.writeDoubleNoTag(doubleObj_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(16, getInnerMessage());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, strObj_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, int32Obj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, int64Obj_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, boolObj_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, bytesObj_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, folatObj_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDoubleObjList().size();
        size += dataSize;
        if (!getDoubleObjList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        doubleObjMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, getInnerMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.bean.protobuf.MessageProtos.Message)) {
        return super.equals(obj);
      }
      com.github.bean.protobuf.MessageProtos.Message other = (com.github.bean.protobuf.MessageProtos.Message) obj;

      boolean result = true;
      result = result && (hasStrObj() == other.hasStrObj());
      if (hasStrObj()) {
        result = result && getStrObj()
            .equals(other.getStrObj());
      }
      result = result && (hasInt32Obj() == other.hasInt32Obj());
      if (hasInt32Obj()) {
        result = result && (getInt32Obj()
            == other.getInt32Obj());
      }
      result = result && (hasInt64Obj() == other.hasInt64Obj());
      if (hasInt64Obj()) {
        result = result && (getInt64Obj()
            == other.getInt64Obj());
      }
      result = result && (hasBoolObj() == other.hasBoolObj());
      if (hasBoolObj()) {
        result = result && (getBoolObj()
            == other.getBoolObj());
      }
      result = result && (hasBytesObj() == other.hasBytesObj());
      if (hasBytesObj()) {
        result = result && getBytesObj()
            .equals(other.getBytesObj());
      }
      result = result && (hasFolatObj() == other.hasFolatObj());
      if (hasFolatObj()) {
        result = result && (
            java.lang.Float.floatToIntBits(getFolatObj())
            == java.lang.Float.floatToIntBits(
                other.getFolatObj()));
      }
      result = result && getDoubleObjList()
          .equals(other.getDoubleObjList());
      result = result && (hasInnerMessage() == other.hasInnerMessage());
      if (hasInnerMessage()) {
        result = result && getInnerMessage()
            .equals(other.getInnerMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStrObj()) {
        hash = (37 * hash) + STROBJ_FIELD_NUMBER;
        hash = (53 * hash) + getStrObj().hashCode();
      }
      if (hasInt32Obj()) {
        hash = (37 * hash) + INT32OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getInt32Obj();
      }
      if (hasInt64Obj()) {
        hash = (37 * hash) + INT64OBJ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInt64Obj());
      }
      if (hasBoolObj()) {
        hash = (37 * hash) + BOOLOBJ_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolObj());
      }
      if (hasBytesObj()) {
        hash = (37 * hash) + BYTESOBJ_FIELD_NUMBER;
        hash = (53 * hash) + getBytesObj().hashCode();
      }
      if (hasFolatObj()) {
        hash = (37 * hash) + FOLATOBJ_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFolatObj());
      }
      if (getDoubleObjCount() > 0) {
        hash = (37 * hash) + DOUBLEOBJ_FIELD_NUMBER;
        hash = (53 * hash) + getDoubleObjList().hashCode();
      }
      if (hasInnerMessage()) {
        hash = (37 * hash) + INNERMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getInnerMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.bean.protobuf.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.bean.protobuf.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.bean.protobuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.bean.protobuf.Message)
        com.github.bean.protobuf.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.bean.protobuf.MessageProtos.internal_static_com_github_bean_protobuf_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.bean.protobuf.MessageProtos.internal_static_com_github_bean_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.bean.protobuf.MessageProtos.Message.class, com.github.bean.protobuf.MessageProtos.Message.Builder.class);
      }

      // Construct using com.github.bean.protobuf.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInnerMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        strObj_ = "hello";
        bitField0_ = (bitField0_ & ~0x00000001);
        int32Obj_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        int64Obj_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        boolObj_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        bytesObj_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        folatObj_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        doubleObj_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        if (innerMessageBuilder_ == null) {
          innerMessage_ = null;
        } else {
          innerMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.bean.protobuf.MessageProtos.internal_static_com_github_bean_protobuf_Message_descriptor;
      }

      public com.github.bean.protobuf.MessageProtos.Message getDefaultInstanceForType() {
        return com.github.bean.protobuf.MessageProtos.Message.getDefaultInstance();
      }

      public com.github.bean.protobuf.MessageProtos.Message build() {
        com.github.bean.protobuf.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.bean.protobuf.MessageProtos.Message buildPartial() {
        com.github.bean.protobuf.MessageProtos.Message result = new com.github.bean.protobuf.MessageProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.strObj_ = strObj_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.int32Obj_ = int32Obj_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.int64Obj_ = int64Obj_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.boolObj_ = boolObj_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bytesObj_ = bytesObj_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.folatObj_ = folatObj_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          doubleObj_ = java.util.Collections.unmodifiableList(doubleObj_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.doubleObj_ = doubleObj_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        if (innerMessageBuilder_ == null) {
          result.innerMessage_ = innerMessage_;
        } else {
          result.innerMessage_ = innerMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.bean.protobuf.MessageProtos.Message) {
          return mergeFrom((com.github.bean.protobuf.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.bean.protobuf.MessageProtos.Message other) {
        if (other == com.github.bean.protobuf.MessageProtos.Message.getDefaultInstance()) return this;
        if (other.hasStrObj()) {
          bitField0_ |= 0x00000001;
          strObj_ = other.strObj_;
          onChanged();
        }
        if (other.hasInt32Obj()) {
          setInt32Obj(other.getInt32Obj());
        }
        if (other.hasInt64Obj()) {
          setInt64Obj(other.getInt64Obj());
        }
        if (other.hasBoolObj()) {
          setBoolObj(other.getBoolObj());
        }
        if (other.hasBytesObj()) {
          setBytesObj(other.getBytesObj());
        }
        if (other.hasFolatObj()) {
          setFolatObj(other.getFolatObj());
        }
        if (!other.doubleObj_.isEmpty()) {
          if (doubleObj_.isEmpty()) {
            doubleObj_ = other.doubleObj_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureDoubleObjIsMutable();
            doubleObj_.addAll(other.doubleObj_);
          }
          onChanged();
        }
        if (other.hasInnerMessage()) {
          mergeInnerMessage(other.getInnerMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStrObj()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.bean.protobuf.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.bean.protobuf.MessageProtos.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object strObj_ = "hello";
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public boolean hasStrObj() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public java.lang.String getStrObj() {
        java.lang.Object ref = strObj_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            strObj_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public com.google.protobuf.ByteString
          getStrObjBytes() {
        java.lang.Object ref = strObj_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strObj_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public Builder setStrObj(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public Builder clearStrObj() {
        bitField0_ = (bitField0_ & ~0x00000001);
        strObj_ = getDefaultInstance().getStrObj();
        onChanged();
        return this;
      }
      /**
       * <code>required string strObj = 1 [default = "hello"];</code>
       */
      public Builder setStrObjBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strObj_ = value;
        onChanged();
        return this;
      }

      private int int32Obj_ ;
      /**
       * <code>optional int32 int32Obj = 2;</code>
       */
      public boolean hasInt32Obj() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       */
      public int getInt32Obj() {
        return int32Obj_;
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       */
      public Builder setInt32Obj(int value) {
        bitField0_ |= 0x00000002;
        int32Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 int32Obj = 2;</code>
       */
      public Builder clearInt32Obj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        int32Obj_ = 0;
        onChanged();
        return this;
      }

      private long int64Obj_ ;
      /**
       * <code>optional int64 int64Obj = 3;</code>
       */
      public boolean hasInt64Obj() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       */
      public long getInt64Obj() {
        return int64Obj_;
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       */
      public Builder setInt64Obj(long value) {
        bitField0_ |= 0x00000004;
        int64Obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 int64Obj = 3;</code>
       */
      public Builder clearInt64Obj() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int64Obj_ = 0L;
        onChanged();
        return this;
      }

      private boolean boolObj_ ;
      /**
       * <code>optional bool boolObj = 12;</code>
       */
      public boolean hasBoolObj() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       */
      public boolean getBoolObj() {
        return boolObj_;
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       */
      public Builder setBoolObj(boolean value) {
        bitField0_ |= 0x00000008;
        boolObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolObj = 12;</code>
       */
      public Builder clearBoolObj() {
        bitField0_ = (bitField0_ & ~0x00000008);
        boolObj_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesObj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes bytesObj = 13;</code>
       */
      public boolean hasBytesObj() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       */
      public com.google.protobuf.ByteString getBytesObj() {
        return bytesObj_;
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       */
      public Builder setBytesObj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bytesObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bytesObj = 13;</code>
       */
      public Builder clearBytesObj() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bytesObj_ = getDefaultInstance().getBytesObj();
        onChanged();
        return this;
      }

      private float folatObj_ ;
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public boolean hasFolatObj() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public float getFolatObj() {
        return folatObj_;
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setFolatObj(float value) {
        bitField0_ |= 0x00000020;
        folatObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float folatObj = 14 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearFolatObj() {
        bitField0_ = (bitField0_ & ~0x00000020);
        folatObj_ = 0F;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> doubleObj_ = java.util.Collections.emptyList();
      private void ensureDoubleObjIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          doubleObj_ = new java.util.ArrayList<java.lang.Double>(doubleObj_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public java.util.List<java.lang.Double>
          getDoubleObjList() {
        return java.util.Collections.unmodifiableList(doubleObj_);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public int getDoubleObjCount() {
        return doubleObj_.size();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public double getDoubleObj(int index) {
        return doubleObj_.get(index);
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public Builder setDoubleObj(
          int index, double value) {
        ensureDoubleObjIsMutable();
        doubleObj_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public Builder addDoubleObj(double value) {
        ensureDoubleObjIsMutable();
        doubleObj_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public Builder addAllDoubleObj(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDoubleObjIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, doubleObj_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>repeated double doubleObj = 15 [packed = true];</code>
       */
      public Builder clearDoubleObj() {
        doubleObj_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private com.github.bean.protobuf.InnerMessageProtos.InnerMessage innerMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.bean.protobuf.InnerMessageProtos.InnerMessage, com.github.bean.protobuf.InnerMessageProtos.InnerMessage.Builder, com.github.bean.protobuf.InnerMessageProtos.InnerMessageOrBuilder> innerMessageBuilder_;
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public boolean hasInnerMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public com.github.bean.protobuf.InnerMessageProtos.InnerMessage getInnerMessage() {
        if (innerMessageBuilder_ == null) {
          return innerMessage_ == null ? com.github.bean.protobuf.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
        } else {
          return innerMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public Builder setInnerMessage(com.github.bean.protobuf.InnerMessageProtos.InnerMessage value) {
        if (innerMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerMessage_ = value;
          onChanged();
        } else {
          innerMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public Builder setInnerMessage(
          com.github.bean.protobuf.InnerMessageProtos.InnerMessage.Builder builderForValue) {
        if (innerMessageBuilder_ == null) {
          innerMessage_ = builderForValue.build();
          onChanged();
        } else {
          innerMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public Builder mergeInnerMessage(com.github.bean.protobuf.InnerMessageProtos.InnerMessage value) {
        if (innerMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              innerMessage_ != null &&
              innerMessage_ != com.github.bean.protobuf.InnerMessageProtos.InnerMessage.getDefaultInstance()) {
            innerMessage_ =
              com.github.bean.protobuf.InnerMessageProtos.InnerMessage.newBuilder(innerMessage_).mergeFrom(value).buildPartial();
          } else {
            innerMessage_ = value;
          }
          onChanged();
        } else {
          innerMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public Builder clearInnerMessage() {
        if (innerMessageBuilder_ == null) {
          innerMessage_ = null;
          onChanged();
        } else {
          innerMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public com.github.bean.protobuf.InnerMessageProtos.InnerMessage.Builder getInnerMessageBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getInnerMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      public com.github.bean.protobuf.InnerMessageProtos.InnerMessageOrBuilder getInnerMessageOrBuilder() {
        if (innerMessageBuilder_ != null) {
          return innerMessageBuilder_.getMessageOrBuilder();
        } else {
          return innerMessage_ == null ?
              com.github.bean.protobuf.InnerMessageProtos.InnerMessage.getDefaultInstance() : innerMessage_;
        }
      }
      /**
       * <code>optional .com.github.bean.protobuf.InnerMessage innerMessage = 16;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.bean.protobuf.InnerMessageProtos.InnerMessage, com.github.bean.protobuf.InnerMessageProtos.InnerMessage.Builder, com.github.bean.protobuf.InnerMessageProtos.InnerMessageOrBuilder> 
          getInnerMessageFieldBuilder() {
        if (innerMessageBuilder_ == null) {
          innerMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.bean.protobuf.InnerMessageProtos.InnerMessage, com.github.bean.protobuf.InnerMessageProtos.InnerMessage.Builder, com.github.bean.protobuf.InnerMessageProtos.InnerMessageOrBuilder>(
                  getInnerMessage(),
                  getParentForChildren(),
                  isClean());
          innerMessage_ = null;
        }
        return innerMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.bean.protobuf.Message)
    }

    // @@protoc_insertion_point(class_scope:com.github.bean.protobuf.Message)
    private static final com.github.bean.protobuf.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.bean.protobuf.MessageProtos.Message();
    }

    public static com.github.bean.protobuf.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.github.bean.protobuf.MessageProtos.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_bean_protobuf_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_bean_protobuf_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\030com.github.bean.protobu" +
      "f\032\022InnerMessage.proto\"\322\001\n\007Message\022\025\n\006str" +
      "Obj\030\001 \002(\t:\005hello\022\020\n\010int32Obj\030\002 \001(\005\022\020\n\010in" +
      "t64Obj\030\003 \001(\003\022\017\n\007boolObj\030\014 \001(\010\022\020\n\010bytesOb" +
      "j\030\r \001(\014\022\024\n\010folatObj\030\016 \001(\002B\002\030\001\022\025\n\tdoubleO" +
      "bj\030\017 \003(\001B\002\020\001\022<\n\014innerMessage\030\020 \001(\0132&.com" +
      ".github.bean.protobuf.InnerMessageB.\n\030co" +
      "m.github.bean.protobufB\rMessageProtosH\001\210" +
      "\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.bean.protobuf.InnerMessageProtos.getDescriptor(),
        }, assigner);
    internal_static_com_github_bean_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_bean_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_bean_protobuf_Message_descriptor,
        new java.lang.String[] { "StrObj", "Int32Obj", "Int64Obj", "BoolObj", "BytesObj", "FolatObj", "DoubleObj", "InnerMessage", });
    com.github.bean.protobuf.InnerMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
