/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.bean.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EnumTypeAvro {
  UNIVERSAL, WEB, IMAGES, LOCAL, NEWS, PRODUCTS, VIDEO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EnumTypeAvro\",\"namespace\":\"com.github.bean.avro\",\"symbols\":[\"UNIVERSAL\",\"WEB\",\"IMAGES\",\"LOCAL\",\"NEWS\",\"PRODUCTS\",\"VIDEO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
