/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.bean.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InnerMessageAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8792286088285559855L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InnerMessageAvro\",\"namespace\":\"com.github.bean.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"enumTypeObj\",\"type\":{\"type\":\"enum\",\"name\":\"EnumTypeAvro\",\"symbols\":[\"UNIVERSAL\",\"WEB\",\"IMAGES\",\"LOCAL\",\"NEWS\",\"PRODUCTS\",\"VIDEO\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int id;
  @Deprecated public com.github.bean.avro.EnumTypeAvro enumTypeObj;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InnerMessageAvro() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param id The new value for id
   * @param enumTypeObj The new value for enumTypeObj
   */
  public InnerMessageAvro(java.lang.CharSequence name, java.lang.Integer id, com.github.bean.avro.EnumTypeAvro enumTypeObj) {
    this.name = name;
    this.id = id;
    this.enumTypeObj = enumTypeObj;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return id;
    case 2: return enumTypeObj;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.Integer)value$; break;
    case 2: enumTypeObj = (com.github.bean.avro.EnumTypeAvro)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'enumTypeObj' field.
   * @return The value of the 'enumTypeObj' field.
   */
  public com.github.bean.avro.EnumTypeAvro getEnumTypeObj() {
    return enumTypeObj;
  }

  /**
   * Sets the value of the 'enumTypeObj' field.
   * @param value the value to set.
   */
  public void setEnumTypeObj(com.github.bean.avro.EnumTypeAvro value) {
    this.enumTypeObj = value;
  }

  /**
   * Creates a new InnerMessageAvro RecordBuilder.
   * @return A new InnerMessageAvro RecordBuilder
   */
  public static com.github.bean.avro.InnerMessageAvro.Builder newBuilder() {
    return new com.github.bean.avro.InnerMessageAvro.Builder();
  }

  /**
   * Creates a new InnerMessageAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InnerMessageAvro RecordBuilder
   */
  public static com.github.bean.avro.InnerMessageAvro.Builder newBuilder(com.github.bean.avro.InnerMessageAvro.Builder other) {
    return new com.github.bean.avro.InnerMessageAvro.Builder(other);
  }

  /**
   * Creates a new InnerMessageAvro RecordBuilder by copying an existing InnerMessageAvro instance.
   * @param other The existing instance to copy.
   * @return A new InnerMessageAvro RecordBuilder
   */
  public static com.github.bean.avro.InnerMessageAvro.Builder newBuilder(com.github.bean.avro.InnerMessageAvro other) {
    return new com.github.bean.avro.InnerMessageAvro.Builder(other);
  }

  /**
   * RecordBuilder for InnerMessageAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InnerMessageAvro>
    implements org.apache.avro.data.RecordBuilder<InnerMessageAvro> {

    private java.lang.CharSequence name;
    private int id;
    private com.github.bean.avro.EnumTypeAvro enumTypeObj;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.bean.avro.InnerMessageAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enumTypeObj)) {
        this.enumTypeObj = data().deepCopy(fields()[2].schema(), other.enumTypeObj);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InnerMessageAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.bean.avro.InnerMessageAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enumTypeObj)) {
        this.enumTypeObj = data().deepCopy(fields()[2].schema(), other.enumTypeObj);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.github.bean.avro.InnerMessageAvro.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.github.bean.avro.InnerMessageAvro.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.github.bean.avro.InnerMessageAvro.Builder setId(int value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.github.bean.avro.InnerMessageAvro.Builder clearId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'enumTypeObj' field.
      * @return The value.
      */
    public com.github.bean.avro.EnumTypeAvro getEnumTypeObj() {
      return enumTypeObj;
    }

    /**
      * Sets the value of the 'enumTypeObj' field.
      * @param value The value of 'enumTypeObj'.
      * @return This builder.
      */
    public com.github.bean.avro.InnerMessageAvro.Builder setEnumTypeObj(com.github.bean.avro.EnumTypeAvro value) {
      validate(fields()[2], value);
      this.enumTypeObj = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'enumTypeObj' field has been set.
      * @return True if the 'enumTypeObj' field has been set, false otherwise.
      */
    public boolean hasEnumTypeObj() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'enumTypeObj' field.
      * @return This builder.
      */
    public com.github.bean.avro.InnerMessageAvro.Builder clearEnumTypeObj() {
      enumTypeObj = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public InnerMessageAvro build() {
      try {
        InnerMessageAvro record = new InnerMessageAvro();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.Integer) defaultValue(fields()[1]);
        record.enumTypeObj = fieldSetFlags()[2] ? this.enumTypeObj : (com.github.bean.avro.EnumTypeAvro) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
